apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 60
  template:
    metadata:
      name: maven-app
      labels:
        app: maven-app
    spec:
      containers:
      - name: maven-app
        image: eagunuworld/mss-maven-web-app:2
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /mss-maven-web-app
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /mss-maven-web-app
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: maven-appsvc
spec:
  type: LoadBalancer
  selector:
    app: maven-app
  ports:
  - port: 80
    targetPort: 8080
    #nodePort: 33333
